os: linux
language: c++
dist: trusty
group: stable
compiler: gcc
sudo: required
notifications:
  email:
    on_success: never
    on_failure: never
addons:
  apt:
    packages:
    - autoconf
    - automake
    - bison
    - build-essential
    - check
    - cmake
    - curl
    - flex
    - g++
    - gcc
    - gcc-multilib
    - gdb
    - git
    - git-man
    - gnupg
    - ibc++-dev
    - inotify-tools
    - libarchive13
    - libbsd-dev
    - libc6-dev
    - libmpfr4
    - libmpfr-dev
    - libncurses5-dev
    - libpython2.7
    - libsubunit0
    - libsubunit-dev
    - libtool
    - lsof
    - make
    - mlocate
    - patch
    - pciutils
    - pkg-config
    - policycoreutils
    - rsync
    - sysstat
    - usbutils
    - valgrind
    - valgrind-dbg
    - wget
before_script:
  - curl --location --output util-linux-2.25.2.tar.gz https://www.kernel.org/pub/linux/utils/util-linux/v2.25/util-linux-2.25.2.tar.gz
  - tar xzvf util-linux-2.25.2.tar.gz && cd util-linux-2.25.2
  - ./configure ADJTIME_PATH=/var/lib/hwclock/adjtime --disable-chfn-chsh --disable-login --disable-nologin --disable-su --disable-setpriv --disable-runuser --disable-pylibmount --disable-static --without-python --without-systemd --without-systemdsystemunitdir --without-ncurses
  - make prlimit && install --verbose --directory $HOME/bin/ && install --verbose --mode=755 prlimit $HOME/bin/prlimit && cd $HOME
script:
  - export HOSTNAME=`hostname`
  - git remote add upstream https://github.com/lavabit/libcore.git
  - git fetch upstream
  - git reset --hard upstream/develop
  - git checkout origin/master -- .travis.yml
  - sed -i "s/CORE_SECURE_MEMORY_LENGTH 65536/CORE_SECURE_MEMORY_LENGTH 57344/g" src/libcore.h
  - grep CORE_SECURE_MEMORY_LENGTH src/libcore.h
  - make core.check libcore.a libcore.so
  - gcc -rdynamic --output='core.check' .objs/check/sample_check.o .objs/check/magma_check.o .objs/check/core/zbase32_check.o .objs/check/core/string_check.o .objs/check/core/core_check.o .objs/check/core/system_check.o .objs/check/core/qp_check.o .objs/check/core/ip_check.o .objs/check/core/qsort_check.o .objs/check/core/checksum_check.o .objs/check/core/inx_check.o .objs/check/core/url_check.o .objs/check/core/base64_check.o .objs/check/core/clamp_check.o .objs/check/core/bitwise_check.o .objs/check/core/linked_check.o .objs/check/core/hashed_check.o .objs/check/core/nbo_check.o .objs/check/core/hex_check.o .objs/check/core/tree_check.o -Wl,--start-group,--whole-archive  libcore.a  -Wl,--no-whole-archive,--end-group  -lresolv -lrt -ldl -lstdc++ -lpthread -lcheck -lsubunit -lm
  - sudo -E "$HOME"/bin/prlimit --pid "$$" --memlock=unlimited:unlimited;
  - $TRAVIS_BUILD_DIR/core.check
  - sudo su -l -c "gdb --batch-silent --eval-command=run $TRAVIS_BUILD_DIR/core.check"
