os: linux
language: c++
dist: trusty
group: stable
compiler: gcc
sudo: required
notifications:
  email:
    recipients:
      - make@magmadaemon.com
    on_success: never
    on_failure: always
addons:
  apt:
    packages:
    - autoconf
    - automake
    - bison
    - build-essential
    - check
    - cmake
    - curl
    - flex
    - g++
    - gcc
    - gcc-multilib
    - gdb
    - git
    - git-man
    - gnupg
    - ibc++-dev
    - inotify-tools
    - libarchive13
    - libbsd-dev
    - libc6-dev
    - libmpfr4
    - libmpfr-dev
    - libncurses5-dev
    - libpython2.7
    - libsubunit0
    - libsubunit-dev
    - libtool
    - lsof
    - make
    - mlocate
    - patch
    - pciutils
    - pkg-config
    - policycoreutils
    - rsync
    - sysstat
    - usbutils
    - valgrind
    - valgrind-dbg
    - wget
before_script:
  - cd $HOME && curl --location --output util-linux-2.25.2.tar.gz https://www.kernel.org/pub/linux/utils/util-linux/v2.25/util-linux-2.25.2.tar.gz
  - tar xzf util-linux-2.25.2.tar.gz && cd util-linux-2.25.2
  - ./configure ADJTIME_PATH=/var/lib/hwclock/adjtime --disable-chfn-chsh --disable-login --disable-nologin --disable-su --disable-setpriv --disable-runuser --disable-pylibmount --disable-static --without-python --without-systemd --without-systemdsystemunitdir --without-ncurses
  - make prlimit && install --verbose --directory $HOME/bin/ && install --verbose --mode=755 prlimit $HOME/bin/prlimit && cd $TRAVIS_BUILD_DIR
script:
  - export HOSTNAME=`hostname`
  - export HASH=`git show  --quiet | grep commit | awk -F' ' '{print $2}'`
  - git remote add upstream https://github.com/lavabit/libcore.git
  - git fetch upstream
  - git reset --hard upstream/develop
  - git checkout $HASH -- .travis.yml
  - sudo -E $HOME/bin/prlimit --pid "$$" --stack=unlimited:unlimited;
  - sudo -E $HOME/bin/prlimit --pid "$$" --memlock=unlimited:unlimited;
  - mkdir .tmp/ && chmod 766 .tmp/ && mkdir .tmp/data/ && chmod 766 .tmp/data/
  - mkdir /tmp/magma/ && chmod 766 /tmp/magma/ && mkdir /tmp/magma/data/ && chmod 766 /tmp/magma/data/
  - make --jobs=4 libcore.a
  - make --jobs=4 libcore.so
  - make --jobs=4 core.check
  - $TRAVIS_BUILD_DIR/core.check
